<a href="https://colab.research.google.com/github/devanshh019/codeexpo/blob/main/FUSION_DATA_TO_FEATURES.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import pickle as pkl
import pandas as pd
import numpy as np
from tqdm import tqdm

In [9]:
with open('/content/vectorizer_text.pkl','rb') as f:
  vectorizer = pkl.load(f)

In [10]:
data=pd.read_pickle('/content/fusion_data.pkl')

In [11]:
data.head()

,text,label,urgency,bg_features,emotion_features
0,oh my god a man is yelling and hitting someone...,domestic_violence,high,"[[-35.249485, -37.8825, -38.30404, -40.274532,...","[[-57.48833, -55.6666, -60.727333, -60.6542, -..."
1,listen flood water is entering houses and peop...,natural_disaster,critical,"[[-22.12311, -17.967926, -22.153316, -20.88747...","[[-77.75856, -77.75856, -59.16552, -46.662754,..."
2,can you help a bike hit a pedestrian and the r...,traffic_accident,high,"[[-31.70082, -27.486843, -29.802658, -30.46683...","[[-63.091873, -63.091873, -63.091873, -63.0918..."
3,can you help a man just snatched a bag and ran...,robbery,high,"[[-42.13351, -37.74229, -42.23981, -40.17144, ...","[[-70.24239, -65.227455, -63.59791, -68.0054, ..."
4,can you help a child fell into the swimming po...,drowning,critical,"[[-24.418259, -29.361618, -31.06563, -33.74666...","[[-62.603725, -61.38896, -54.294243, -51.48111..."

In [12]:
text_vectors = vectorizer.transform(data["text"]).toarray()

In [13]:
data['text']=list(text_vectors)

In [14]:
data

,text,label,urgency,bg_features,emotion_features
0,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",domestic_violence,high,"[[-35.249485, -37.8825, -38.30404, -40.274532,...","[[-57.48833, -55.6666, -60.727333, -60.6542, -..."
1,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",natural_disaster,critical,"[[-22.12311, -17.967926, -22.153316, -20.88747...","[[-77.75856, -77.75856, -59.16552, -46.662754,..."
2,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",traffic_accident,high,"[[-31.70082, -27.486843, -29.802658, -30.46683...","[[-63.091873, -63.091873, -63.091873, -63.0918..."
3,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.47162759...",robbery,high,"[[-42.13351, -37.74229, -42.23981, -40.17144, ...","[[-70.24239, -65.227455, -63.59791, -68.0054, ..."
4,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",drowning,critical,"[[-24.418259, -29.361618, -31.06563, -33.74666...","[[-62.603725, -61.38896, -54.294243, -51.48111..."
...,...,...,...,...,...
9995,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",animal_attack,medium,"[[-61.46856, -66.9802, -80.0, -76.16774, -76.2...","[[-52.106934, -41.985394, -40.17047, -43.25325..."
9996,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",medical_emergency,high,"[[-37.355408, -34.491585, -33.010387, -32.3881...","[[-66.14762, -66.14762, -66.14762, -66.14762, ..."
9997,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",explosion,critical,"[[-33.384254, -33.845196, -34.227936, -28.9642...","[[-41.044964, -41.304283, -39.99205, -38.36587..."
9998,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",traffic_accident,high,"[[-24.95451, -19.886234, -22.652643, -23.16510...","[[-54.870964, -50.193485, -48.705902, -45.8039..."
9999,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",suspicious_activity,medium,"[[-22.118546, -16.288986, -18.721405, -16.0519...","[[-66.46552, -63.863605, -66.87221, -66.87221,..."

In [15]:
data['text'][0].shape

(199,)

In [16]:
import tensorflow as tf

text_model = tf.keras.models.load_model("/content/text_model.keras")

emotion_model = tf.keras.models.load_model("/content/ravdees-2.keras")

sound_model = tf.keras.models.load_model("/content/background_model.keras")

In [17]:
text_model.summary()
#feature layer is -2

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_12 (Dense)                │ (None, 512)            │       102,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_6 (Dropout)             │ (None, 512)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_13 (Dense)                │ (None, 256)            │       131,328 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_7 (Dropout)             │ (None, 256)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_14 (Dense)                │ (None, 128)            │        32,896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_15 (Dense)                │ (None, 13)             │         1,677 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 804,905 (3.07 MB)

 Trainable params: 268,301 (1.02 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 536,604 (2.05 MB)

In [18]:
emotion_model.summary()
#feature layer is -3

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 126, 198, 32)   │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 63, 99, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 61, 97, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 30, 48, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_2 (Conv2D)               │ (None, 28, 46, 128)    │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_2 (MaxPooling2D)  │ (None, 14, 23, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pooling2d        │ (None, 128)            │             0 │
│ (GlobalAveragePooling2D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 128)            │        16,512 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 8)              │         1,032 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 330,650 (1.26 MB)

 Trainable params: 110,216 (430.53 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 220,434 (861.07 KB)

In [19]:
sound_model.summary()
#feature layer is -3

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_3 (Conv2D)               │ (None, 126, 172, 32)   │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_3           │ (None, 126, 172, 32)   │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_3 (MaxPooling2D)  │ (None, 63, 86, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_4 (Conv2D)               │ (None, 61, 84, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_4           │ (None, 61, 84, 64)     │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_4 (MaxPooling2D)  │ (None, 30, 42, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_5 (Conv2D)               │ (None, 28, 40, 128)    │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_5           │ (None, 28, 40, 128)    │           512 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_5 (MaxPooling2D)  │ (None, 14, 20, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_1 (Flatten)             │ (None, 35840)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 256)            │     9,175,296 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 256)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 128)            │        32,896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_3 (Dropout)             │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 10)             │         1,290 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 27,908,256 (106.46 MB)

 Trainable params: 9,302,602 (35.49 MB)

 Non-trainable params: 448 (1.75 KB)

 Optimizer params: 18,605,206 (70.97 MB)

In [20]:
dummy = np.zeros((1, len(data["text"][0])))
text_model.predict(dummy)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 225ms/step

array([[0.06757579, 0.05259109, 0.14489675, 0.07797948, 0.05932057,
        0.09648391, 0.15336412, 0.05127   , 0.05542906, 0.05332412,
        0.05963798, 0.05624368, 0.07188348]], dtype=float32)

In [21]:
text_feature_model = tf.keras.Model(
    inputs=text_model.inputs,
    outputs=text_model.layers[-2].output
)

In [22]:
dummy = np.zeros((1,128,200,1))
emotion_model.predict(dummy)

emotion_feature_model = tf.keras.Model(
    inputs=emotion_model.inputs,
    outputs=emotion_model.layers[-3].output
)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 452ms/step

In [23]:
dummy = np.zeros((1,128,174,1))
sound_model.predict(dummy)

sound_feature_model = tf.keras.Model(
    inputs=sound_model.inputs,
    outputs=sound_model.layers[-3].output
)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 798ms/step

In [24]:
sound_feature_model.summary()

Model: "functional_81"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_1 (InputLayer)      │ (None, 128, 174, 1)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_3 (Conv2D)               │ (None, 126, 172, 32)   │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_3           │ (None, 126, 172, 32)   │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_3 (MaxPooling2D)  │ (None, 63, 86, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_4 (Conv2D)               │ (None, 61, 84, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_4           │ (None, 61, 84, 64)     │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_4 (MaxPooling2D)  │ (None, 30, 42, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_5 (Conv2D)               │ (None, 28, 40, 128)    │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_5           │ (None, 28, 40, 128)    │           512 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_5 (MaxPooling2D)  │ (None, 14, 20, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_1 (Flatten)             │ (None, 35840)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 256)            │     9,175,296 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 256)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 128)            │        32,896 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9,301,760 (35.48 MB)

 Trainable params: 9,301,312 (35.48 MB)

 Non-trainable params: 448 (1.75 KB)

In [25]:
emotion_feature_model.summary()

Model: "functional_80"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)        │ (None, 128, 200, 1)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d (Conv2D)                 │ (None, 126, 198, 32)   │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 63, 99, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 61, 97, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 30, 48, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_2 (Conv2D)               │ (None, 28, 46, 128)    │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_2 (MaxPooling2D)  │ (None, 14, 23, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pooling2d        │ (None, 128)            │             0 │
│ (GlobalAveragePooling2D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 128)            │        16,512 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 109,184 (426.50 KB)

 Trainable params: 109,184 (426.50 KB)

 Non-trainable params: 0 (0.00 B)

In [26]:
text_feature_model.summary()

Model: "functional_79"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_3 (InputLayer)      │ (None, 199)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_12 (Dense)                │ (None, 512)            │       102,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_6 (Dropout)             │ (None, 512)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_13 (Dense)                │ (None, 256)            │       131,328 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_7 (Dropout)             │ (None, 256)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_14 (Dense)                │ (None, 128)            │        32,896 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 266,624 (1.02 MB)

 Trainable params: 266,624 (1.02 MB)

 Non-trainable params: 0 (0.00 B)

GENERATING TEXT FEATURES

In [27]:
text_vectors = np.stack(data["text"].values)

In [28]:
text_features = text_feature_model.predict(text_vectors, verbose=1)

WARNING:tensorflow:5 out of the last 5 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x7f7780177a60> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step

In [29]:
feature_data=pd.DataFrame()

In [30]:
feature_data['text']=list(text_features)

EMOTION FEATURES

In [31]:
emotion_mfcc=[]

In [32]:
for mfcc in tqdm(data['emotion_features']):
  mfcc=(np.array(mfcc)).reshape(1,128,200,1)
  features=emotion_feature_model.predict(mfcc,verbose=0)
  emotion_mfcc.append(features[0])

100%|██████████| 10000/10000 [13:51<00:00, 12.03it/s]

In [33]:
emotion_mfcc[0].shape

(128,)

In [34]:
feature_data['emotion']=emotion_mfcc

BACKGROUND SOUNF FEATURES

In [45]:
sound_feature=[]

In [46]:
data['bg_features'][0].shape

(128, 174)

In [47]:
for mel in tqdm(data['bg_features']):
  mel = np.array(mel).reshape(1,128,174,1)
  features=sound_feature_model.predict(mel,verbose=0)
  sound_feature.append(features[0])

100%|██████████| 10000/10000 [14:11<00:00, 11.75it/s]

In [49]:
np.array(data['bg_features'][0]).shape

(128, 174)

In [50]:
feature_data['sound']=sound_feature

In [51]:
print(len(feature_data['text'][0]))
print(len(feature_data['emotion'][0]))
print(len(feature_data['sound'][0]))

128
128
128

In [53]:
feature_data['label'] = data['label']
feature_data['urgency'] = data['urgency']

In [54]:
feature_data.head()

,text,emotion,sound,label,urgency
0,"[1.3008546, 1.864815, 0.05988244, 0.46803075, ...","[2.0342631, 0.0, 0.0, 0.0, 0.24019876, 0.0, 0....","[0.0, 0.0, 0.48752624, 0.0, 0.0, 0.0, 4.949202...",domestic_violence,high
1,"[1.8029424, 0.9326464, 0.60693604, 0.5036978, ...","[2.5705042, 0.0, 0.0, 0.0, 0.19596168, 0.0, 0....","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 5.575213, ...",natural_disaster,critical
2,"[1.0551035, 1.8775334, 1.1153818, 0.499948, 1....","[0.0, 0.9417129, 0.0, 0.0, 0.4723828, 0.0, 0.0...","[0.0, 3.4388413, 14.071653, 18.365202, 0.0, 0....",traffic_accident,high
3,"[0.0, 0.566012, 0.0, 0.09775583, 2.0740426, 2....","[2.8442686, 0.0, 0.0, 0.0, 0.7452919, 0.0, 0.0...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 3.1266816, 1.62...",robbery,high
4,"[0.74268353, 2.2943003, 0.8214513, 1.300232, 0...","[0.0, 0.7532223, 1.0385139, 0.0035024174, 0.0,...","[0.0, 13.090834, 0.0, 0.0, 0.0, 0.0, 2.5996318...",drowning,critical

In [55]:
feature_data.to_pickle("fusion_features_dataset.pkl")